### ISSUE TITLE
Not installable on MSSMS 2016

### ISSUE THREAD

**Issue by chrisbra** [devvcat/ssms-executor#4]
Hi, I took the latest release zip file, extracted it and run the SSMSExecute.vsix. However, the installation aborted on a
```
Microsoft SQL Server Management Studio      13.0.16106.4
Microsoft Analysis Services Client Tools    13.0.1700.441
Microsoft Data Access Components (MDAC)     6.3.9600.17415
Microsoft MSXML                             3.0 6.0
Microsoft Internet Explorer                 9.11.9600.18639
Microsoft .NET Framework                    4.0.30319.42000
Operating System                            6.3.9600
```
with the following error message:
```
02.05.2017 09:37:59 - Microsoft VSIX Installer
02.05.2017 09:37:59 - -------------------------------------------
02.05.2017 09:37:59 - Initializing Install...
02.05.2017 09:37:59 - Extension Details...
02.05.2017 09:37:59 - 	Identifier      : SSMSExecutor.17e8fa63-4183-460e-8840-f8b2293f545c
02.05.2017 09:37:59 - 	Name            : SSMS Executor
02.05.2017 09:37:59 - 	Author          : Stanislav Stoyanov
02.05.2017 09:37:59 - 	Version         : 1.0
02.05.2017 09:37:59 - 	Description     : SSMS Executor is a SQL Server Management Studio Add-in for executing the current statement, based on the cursor position.
02.05.2017 09:37:59 - 	Locale          : en-US
02.05.2017 09:37:59 - 	MoreInfoURL     : http://devvcat.com/
02.05.2017 09:37:59 - 	InstalledByMSI  : False
02.05.2017 09:37:59 - 	SupportedFrameworkVersionRange : [4.5,)
02.05.2017 09:37:59 - 
02.05.2017 09:37:59 - 	Supported Products : 
02.05.2017 09:37:59 - 		Microsoft.VisualStudio.Community
02.05.2017 09:37:59 - 			Version : [14.0,15.0]
02.05.2017 09:37:59 - 		Microsoft.VisualStudio.IntegratedShell
02.05.2017 09:37:59 - 			Version : [14.0,15.0)
02.05.2017 09:37:59 - 
02.05.2017 09:37:59 - 	References      : 
02.05.2017 09:37:59 - 		-------------------------------------------------------
02.05.2017 09:37:59 - 		Identifier   : Microsoft.VisualStudio.MPF.14.0
02.05.2017 09:37:59 - 		Name         : Visual Studio MPF 14.0
02.05.2017 09:37:59 - 		Version      : [14.0]
02.05.2017 09:37:59 - 		MoreInfoURL  : 
02.05.2017 09:37:59 - 		Nested       : No
02.05.2017 09:37:59 - 
02.05.2017 09:37:59 - 
02.05.2017 09:37:59 - Searching for applicable products...
02.05.2017 09:38:00 - Found installed product - Global Location
02.05.2017 09:38:00 - Found installed product - ssms
02.05.2017 09:38:00 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

**Comment by devvcat** [comment]
Hi @chrisbra,

please extract the .zip content into SSMS 2016 extension folder. Close SSMS. After the first start you will see message, please click 'No' and restart SSMS.

> The 'ExecutorPackage' package did not load correctly

SSMS 2016 Extensions location
    C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\ManagementStudio\Extensions

Stanislav

**Comment by chrisbra** [comment]
okay, that worked. However after restarting ssms `CTRL-Shift-E` does nothing. Do I have to configure it somehow?

**Comment by devvcat** [comment]
Can you confirm that you placed the content of the '.zip' into the extension folder.
After the first restart did you get the error message "The 'ExecutorPackage' package did not load correctly"
Did you click 'No'. Did you restart again SSMS. Do you have any other add-in with the same keybinding.

Please check the other thread for similar issue https://github.com/devvcat/ssms-executor/issues/1#issuecomment-252637184

Stanislav

**Comment by chrisbra** [comment]
Hi,
extracted the zip file into:
`E:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\ManagementStudio\Extensions\SSMSExecutor`
Got the mentioned error messaged and clicked 'no' and restarted SSMS several times.

However, I don't see the mentioned icon and don't have the `SSMSExecutor` option in the keyboard settings. Not sure what else to check from issue #1

**Comment by devvcat** [comment]
Hi, if you want we can schedule a quick TeamViewer session to take a look.
You can find my email as part of the commits, issue an `git log` command and message me if you want.

Stanislav

**Comment by unformatt** [comment]
So what I'm reading here is that it's normal to get this message? Should probably include that information in the installation instructions.

![image](https://user-images.githubusercontent.com/157132/28587983-e74177dc-7146-11e7-8e7e-45f4021df64f.png)

**Comment by ikoiko** [comment]
Any update of this issue ? did u make tw session and fix the problem ?

**Comment by vivek201** [comment]
@ikoiko I was just having this problem and opening the Management Studio as Administration fixed the issue for me. Hope it works for you as well.

**Comment by orlandoseixas** [comment]
I had the same issue. But it was resolved using the automatic installer: SSMSExecutor-2.0.2-alpha.exe
